module.exports = require('next-routes')()
  .add('HomePage', '/')
  .add('PartiesPage', '/agenda')
  .add('PartyPage', '/agenda/:slug')
  .add('VipPage', '/reservas')
  .add('BirthPage', '/aniversarios')
  .add('AlbumsPage', '/fotos')
  .add('AlbumPage', '/fotos/:album')
  .add('PhotoPage', '/fotos/:album/:photoSlug')
